/**
 * @file ComplaintDetailScreen.styles.ts
 * @feature Complaints / Styles
 * @responsibility Shared styles factory for ComplaintDetailScreen component.
 */

import { StyleSheet } from 'react-native';
import { spacing, radius } from '@theme/index';

export const makeStyles = (colors: any, bottomInset: number) => {
  const safeBottom = bottomInset > 0 ? bottomInset : 16;
  return StyleSheet.create({
    container: {
      paddingHorizontal: spacing.lg,
      flex: 1,
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.status.dangerBg,
      padding: spacing.sm + 2,
      borderRadius: radius.sm,
      marginBottom: spacing.sm,
      gap: spacing.xs,
    },
    errorText: {
      flex: 1,
      color: colors.status.danger,
    },
    retryText: {
      color: colors.status.danger,
      fontWeight: '700',
    },
    loaderCenter: {
      paddingVertical: spacing.xxl,
      alignItems: 'center',
    },
    loadingText: {
      color: colors.text.muted,
      marginTop: spacing.sm,
    },
    scrollContent: {
      paddingTop: 0,
      paddingBottom: safeBottom + 40,
    },
    heroCard: {
      marginBottom: spacing.md,
    },
    heroHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: spacing.xs,
    },
    headerLeftGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    typeBadgeWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.neutral[100],
      paddingHorizontal: spacing.xs + 2,
      paddingVertical: 2,
      borderRadius: radius.sm,
      gap: 3,
    },
    typeBadgeText: {
      fontSize: 10,
      fontWeight: '600',
    },
    titleText: {
      marginTop: 2,
    },
    pillRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginTop: spacing.xs + 2,
    },
    appliancePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.neutral[100],
      paddingHorizontal: spacing.sm,
      paddingVertical: 3,
      borderRadius: radius.pill,
    },
    issuePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.status.warningBg,
      paddingHorizontal: spacing.sm,
      paddingVertical: 3,
      borderRadius: radius.pill,
    },
    servicePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.primary.light,
      paddingHorizontal: spacing.sm,
      paddingVertical: 3,
      borderRadius: radius.pill,
    },
    pillText: {
      fontWeight: '600',
      fontSize: 11,
    },
    warningPillText: {
      fontWeight: '600',
      fontSize: 11,
      color: colors.status.warning,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border.light,
      marginVertical: spacing.sm + 2,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginVertical: 4,
      gap: spacing.sm,
    },
    infoContent: {
      flex: 1,
    },
    descriptionText: {
      marginTop: 2,
      lineHeight: 20,
    },
    warrantyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: spacing.sm,
      paddingTop: spacing.xs + 2,
      borderTopWidth: 1,
      borderTopColor: colors.border.light,
      gap: spacing.xs,
    },
    warrantyCoveredText: {
      flex: 1,
      color: colors.category.emeraldIcon,
    },
    warrantyNonCoveredText: {
      flex: 1,
      color: colors.text.muted,
    },
    slotTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    dualOtpCard: {
      backgroundColor: colors.background.paper,
      borderColor: colors.border.light || colors.neutral[200],
      borderWidth: 1,
      marginBottom: spacing.md,
      borderRadius: radius.lg,
    },
    dualOtpHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    dualOtpHeaderThumb: {
      width: 38,
      height: 38,
      borderRadius: radius.md,
      backgroundColor: colors.primary.light,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dualOtpHeaderContent: {
      flex: 1,
    },
    otpStepCard: {
      marginTop: spacing.xs,
    },
    otpStepTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.sm,
      marginBottom: spacing.xs,
    },
    otpStepLabelGroup: {
      flex: 1,
    },
    otpStepDesc: {
      marginTop: 2,
      lineHeight: 16,
    },
    otpCodeBoxActive: {
      backgroundColor: colors.primary.light,
      borderColor: colors.primary.main,
      borderWidth: 1.5,
      borderRadius: radius.md,
      paddingVertical: spacing.xs + 2,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 6,
      position: 'relative',
    },
    otpCodeBoxWarning: {
      backgroundColor: colors.status.warningBg,
      borderColor: colors.status.warning,
      borderWidth: 1.5,
      borderRadius: radius.md,
      paddingVertical: spacing.xs + 2,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 6,
      position: 'relative',
    },
    otpCodeBoxVerified: {
      backgroundColor: colors.status.successBg,
      borderColor: colors.status.success,
      borderWidth: 1,
      borderRadius: radius.md,
      paddingVertical: spacing.xs + 2,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 6,
      position: 'relative',
    },
    otpCodeBoxNeutral: {
      backgroundColor: colors.neutral[100],
      borderColor: colors.neutral[300],
      borderWidth: 1,
      borderRadius: radius.md,
      paddingVertical: spacing.xs + 2,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 6,
      position: 'relative',
    },
    otpCodeTextPrimary: {
      color: colors.primary.main,
      fontWeight: '800',
      letterSpacing: 4,
    },
    otpCodeTextWarning: {
      color: colors.status.warning,
      fontWeight: '800',
      letterSpacing: 4,
    },
    otpCodeTextVerified: {
      color: colors.status.success,
      fontWeight: '700',
      letterSpacing: 4,
    },
    otpCodeTextNeutral: {
      color: colors.text.secondary,
      fontWeight: '700',
      letterSpacing: 4,
    },
    otpVerifiedIndicator: {
      position: 'absolute',
      right: 12,
    },
    dualOtpDivider: {
      height: 1,
      backgroundColor: colors.border.light || colors.neutral[200],
      marginVertical: spacing.sm + 2,
    },
    dualOtpSecurityBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.neutral[100],
      borderRadius: radius.sm,
      paddingHorizontal: spacing.sm,
      paddingVertical: 6,
      marginTop: spacing.sm + 2,
    },
    securityBarText: {
      flex: 1,
      fontSize: 11,
      lineHeight: 14,
    },
    sectionTitle: {
      marginBottom: spacing.xs + 2,
      marginTop: spacing.xs,
    },
    applianceCard: {
      marginBottom: spacing.md,
      overflow: 'hidden',
    },
    applianceRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
    },
    applianceIconThumb: {
      width: 40,
      height: 40,
      borderRadius: radius.md,
      backgroundColor: colors.primary.light,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      marginTop: 2,
    },
    applianceInfo: {
      flex: 1,
      minWidth: 0,
    },
    applianceMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
      marginTop: 2,
    },
    applianceWarrantyChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 6,
    },
    technicianCard: {
      marginBottom: spacing.sm,
      overflow: 'hidden',
    },
    techRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm + 2,
    },
    techAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary.light,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    pendingTechAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.neutral[100],
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    techInfo: {
      flex: 1,
      minWidth: 0,
    },
    techHeaderLine: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.xs,
    },
    techDesignation: {
      marginTop: 2,
    },
    phoneButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      backgroundColor: colors.primary.light,
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
      borderRadius: radius.pill,
      marginTop: 4,
    },
    dealerPhoneButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.category.indigoBg,
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
      borderRadius: radius.pill,
    },
    dealerEmailButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.neutral[100],
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
      borderRadius: radius.pill,
      maxWidth: 180,
    },
    customerEmailButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.neutral[100],
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
      borderRadius: radius.pill,
      maxWidth: 180,
    },
    contactActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginTop: 4,
    },
    dealerPhoneText: {
      fontWeight: '700',
      color: colors.category.indigoIcon,
    },
    contactPhoneText: {
      fontWeight: '700',
      color: colors.primary.main,
    },
    metaSpacing: {
      marginTop: 4,
    },
    dealerCard: {
      marginBottom: spacing.md,
      overflow: 'hidden',
    },
    dealerRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
    },
    dealerIconThumb: {
      width: 36,
      height: 36,
      borderRadius: radius.md,
      backgroundColor: colors.category.indigoBg,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      marginTop: 2,
    },
    dealerInfo: {
      flex: 1,
      minWidth: 0,
    },
    customerCard: {
      marginBottom: spacing.md,
      overflow: 'hidden',
    },
    customerRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
    },
    customerIconThumb: {
      width: 36,
      height: 36,
      borderRadius: radius.md,
      backgroundColor: colors.primary.light,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      marginTop: 2,
    },
    customerInfo: {
      flex: 1,
      minWidth: 0,
    },
    addressText: {
      marginTop: 4,
      lineHeight: 18,
    },
    timelineCard: {
      marginBottom: spacing.md,
      overflow: 'hidden',
    },
    partsCard: {
      marginBottom: spacing.md,
      overflow: 'hidden',
    },
    partItemRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: spacing.xs + 2,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.light,
      gap: spacing.sm,
    },
    partItemLeft: {
      flex: 1,
      minWidth: 0,
    },
    partItemRight: {
      alignItems: 'flex-end',
      flexShrink: 0,
    },
    partCostText: {
      fontWeight: '700',
      textAlign: 'right',
    },
    partsSubtotalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: spacing.sm,
      marginTop: spacing.xs,
      gap: spacing.sm,
    },
    partSubtotalRight: {
      alignItems: 'flex-end',
      flexShrink: 0,
    },
    visitCard: {
      marginBottom: spacing.sm,
    },
    visitHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    visitTechInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    notesBox: {
      backgroundColor: colors.neutral[100],
      padding: spacing.sm,
      borderRadius: radius.sm,
      marginTop: spacing.sm,
    },
    estimateCard: {
      marginBottom: spacing.md,
      overflow: 'hidden',
    },
    estimateIconThumb: {
      width: 36,
      height: 36,
      borderRadius: radius.md,
      backgroundColor: colors.primary.light,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    estimateNoticeBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.neutral[100],
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs + 2,
      borderRadius: radius.sm,
      marginTop: spacing.sm,
      gap: spacing.xs,
    },
    estimateNoticeText: {
      flex: 1,
      lineHeight: 16,
    },
    invoiceCard: {
      marginBottom: spacing.md,
      overflow: 'hidden',
    },
    invoiceHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.sm,
    },
    invoiceHeaderLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      minWidth: 0,
    },
    invoiceIconThumb: {
      width: 36,
      height: 36,
      borderRadius: radius.md,
      backgroundColor: colors.primary.light,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    invoiceTitleWrap: {
      flex: 1,
      minWidth: 0,
    },
    billRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: spacing.xs,
      gap: spacing.sm,
    },
    billItemLeft: {
      flex: 1,
      minWidth: 0,
    },
    billLabel: {
      lineHeight: 18,
    },
    billAmount: {
      fontWeight: '600',
      textAlign: 'right',
      flexShrink: 0,
    },
    warrantySavingBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.category.emeraldBg || '#DCFCE7',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs + 2,
      borderRadius: radius.sm,
      marginVertical: spacing.xs,
      gap: spacing.xs,
    },
    warrantySavingText: {
      color: colors.category.emeraldIcon || '#15803D',
      fontWeight: '700',
      flex: 1,
      fontSize: 11,
    },
    totalBillRow: {
      marginTop: 0,
      paddingTop: 0,
    },
    totalAmountText: {
      fontWeight: '800',
      textAlign: 'right',
      flexShrink: 0,
    },
    reviewCard: {
      marginBottom: spacing.md,
      backgroundColor: colors.background.paper,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.border.light,
    },
    reviewedBox: {
      gap: spacing.xs,
    },
    reviewHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    reviewStarGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    feedbackQuote: {
      fontStyle: 'italic',
      marginTop: spacing.xs,
      color: colors.text.secondary,
    },
    unreviewedBox: {
      gap: spacing.sm,
    },
    ratingPromptRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    ratingPromptIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.category.orangeBg || '#FEF3C7',
      alignItems: 'center',
      justifyContent: 'center',
    },
    ratingPromptTextWrap: {
      flex: 1,
    },
    reviewCtaBtn: {
      marginTop: spacing.xs,
    },
    actionBtnSection: {
      marginTop: spacing.sm,
      gap: spacing.sm,
    },
    btnRow: {
      flexDirection: 'row',
      gap: spacing.sm,
    },
    flexBtn: {
      flex: 1,
    },
    fullWidthBtn: {
      width: '100%',
    },
    boldText: {
      fontWeight: '700',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.background.paper,
      borderTopLeftRadius: radius.xl,
      borderTopRightRadius: radius.xl,
      padding: spacing.lg,
      paddingBottom: safeBottom + 16,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: spacing.md,
    },
    modalSlotRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: spacing.sm + 2,
      paddingHorizontal: spacing.sm,
      borderRadius: radius.md,
      backgroundColor: colors.neutral[100],
      marginBottom: spacing.xs,
      gap: spacing.sm,
    },
    modalSlotText: {
      flex: 1,
      fontWeight: '600',
    },
    rescheduleSectionTitle: {
      fontWeight: '700',
      fontSize: 11,
      letterSpacing: 0.5,
      marginTop: spacing.sm,
      marginBottom: spacing.xs + 2,
    },
    dateScrollWrap: {
      gap: spacing.xs + 2,
      paddingVertical: spacing.xs,
    },
    dateChip: {
      paddingVertical: spacing.xs + 2,
      paddingHorizontal: spacing.sm + 4,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.border.main || colors.neutral[300],
      backgroundColor: colors.background.paper,
      alignItems: 'center',
      minWidth: 72,
    },
    dateChipSub: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.text.secondary,
      marginBottom: 2,
    },
    dateChipMain: {
      fontWeight: '700',
      color: colors.text.primary,
    },
    slotsGridWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs + 2,
      marginVertical: spacing.xs,
    },
    slotChipGrid: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: spacing.xs + 2,
      paddingHorizontal: spacing.sm,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.border.main || colors.neutral[300],
      backgroundColor: colors.background.paper,
    },
    slotChipTextGrid: {
      fontWeight: '600',
      fontSize: 11,
      color: colors.text.primary,
    },
    rescheduleSummaryBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      padding: spacing.md,
      borderRadius: radius.md,
      backgroundColor: colors.primary.light || '#EFF6FF',
      marginTop: spacing.md,
      borderWidth: 1,
      borderColor: colors.primary.main || '#3B82F6',
    },
  });
};
